# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mdetect',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/mdetect',
                'lib_path': 'mdetect'},
  'syms': {'mdetect.core': {'mdetect.core.foo': ('core.html#foo', 'mdetect/core.py')}}}
